Fix for leading slashes in the current directory
Konamiman/RookieDrive-FDD-ROM pull request #9
Opened 2024-12-26 23:43 UTC by cristianoag

Hi Nestor, I converted your DiskROM to Konami SCC so it can work with the MSXUSB. During the process, I noticed that the code was adding unnecessary slashes to the current directory. To address this, I wrote a small routine to ensure that directories are printed with only a single leading slash. Just wanted to contribute and help out!

2025-01-03 16:10 UTC, Konamiman requested changes

2025-01-03 16:10 UTC, Konamiman commented on msx/bank1/boot_menu.asm
> +    ;jr _BM_PRINT_CUR_DIR_END
If this code is no longer used it's better to just remove it, and the same for the `;call PRINT` below.

2025-01-03 16:10 UTC, Konamiman commented on msx/callbnk.asm
> +; - Ensures correct switching before and after the routine call.
I understand that this applies to your own fork of the code but not to the changes in this pull request, right? In that case it's better to remove these comments.

2025-01-03 16:10 UTC, Konamiman commented
Hi @cristianoag, good timing as I'm preparing a new release. I have left a couple of comments, also could you please provide more details in the pull request description? How to reproduce the issue in the original code, and how it will look like with your fix? Even better if you can provide screenshots. Thanks!
-

2025-01-05 16:47 UTC, cristianoag commented
You're right. Let me do the right changes and create another PR with more detail. Then you will have everything to evaluate.

2025-01-05 16:47 UTC, closed without merging